[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "faker>=37.3.0",
    "fastapi==0.104.1",
    "uvicorn[standard]==0.24.0",
    "strawberry-graphql[fastapi]==0.213.0",
    "zeep"
]
