# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"\x07\n\x05\x45mpty\"$\n\x0eUsuarioRequest\x12\x12\n\nid_usuario\x18\x01 \x01(\t\"&\n\x0fPlaylistRequest\x12\x13\n\x0bid_playlist\x18\x01 \x01(\t\"\"\n\rMusicaRequest\x12\x11\n\tid_musica\x18\x01 \x01(\t\"2\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05idade\x18\x03 \x01(\x05\"M\n\x06Musica\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07\x61rtista\x18\x03 \x01(\t\x12\x18\n\x10\x64uracao_segundos\x18\x04 \x01(\x05\"I\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x12\n\nid_usuario\x18\x03 \x01(\t\x12\x0f\n\x07musicas\x18\x04 \x03(\t\"8\n\x10UsuariosResponse\x12$\n\x08usuarios\x18\x01 \x03(\x0b\x32\x12.streaming.Usuario\"5\n\x0fMusicasResponse\x12\"\n\x07musicas\x18\x01 \x03(\x0b\x32\x11.streaming.Musica\";\n\x11PlaylistsResponse\x12&\n\tplaylists\x18\x01 \x03(\x0b\x32\x13.streaming.Playlist\"\x96\x01\n\x14\x45statisticasResponse\x12\x16\n\x0etotal_usuarios\x18\x01 \x01(\x05\x12\x15\n\rtotal_musicas\x18\x02 \x01(\x05\x12\x17\n\x0ftotal_playlists\x18\x03 \x01(\x05\x12\"\n\x1amedia_musicas_por_playlist\x18\x04 \x01(\x02\x12\x12\n\ntecnologia\x18\x05 \x01(\t2\x9e\x04\n\x10StreamingService\x12\x44\n\x13ListarTodosUsuarios\x12\x10.streaming.Empty\x1a\x1b.streaming.UsuariosResponse\x12\x42\n\x12ListarTodasMusicas\x12\x10.streaming.Empty\x1a\x1a.streaming.MusicasResponse\x12Q\n\x16ListarPlaylistsUsuario\x12\x19.streaming.UsuarioRequest\x1a\x1c.streaming.PlaylistsResponse\x12O\n\x15ListarMusicasPlaylist\x12\x1a.streaming.PlaylistRequest\x1a\x1a.streaming.MusicasResponse\x12R\n\x18ListarPlaylistsComMusica\x12\x18.streaming.MusicaRequest\x1a\x1c.streaming.PlaylistsResponse\x12\x46\n\x11ObterEstatisticas\x12\x10.streaming.Empty\x1a\x1f.streaming.EstatisticasResponse\x12@\n\rStreamMusicas\x12\x18.streaming.MusicaRequest\x1a\x11.streaming.Musica(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_USUARIOREQUEST']._serialized_start=39
  _globals['_USUARIOREQUEST']._serialized_end=75
  _globals['_PLAYLISTREQUEST']._serialized_start=77
  _globals['_PLAYLISTREQUEST']._serialized_end=115
  _globals['_MUSICAREQUEST']._serialized_start=117
  _globals['_MUSICAREQUEST']._serialized_end=151
  _globals['_USUARIO']._serialized_start=153
  _globals['_USUARIO']._serialized_end=203
  _globals['_MUSICA']._serialized_start=205
  _globals['_MUSICA']._serialized_end=282
  _globals['_PLAYLIST']._serialized_start=284
  _globals['_PLAYLIST']._serialized_end=357
  _globals['_USUARIOSRESPONSE']._serialized_start=359
  _globals['_USUARIOSRESPONSE']._serialized_end=415
  _globals['_MUSICASRESPONSE']._serialized_start=417
  _globals['_MUSICASRESPONSE']._serialized_end=470
  _globals['_PLAYLISTSRESPONSE']._serialized_start=472
  _globals['_PLAYLISTSRESPONSE']._serialized_end=531
  _globals['_ESTATISTICASRESPONSE']._serialized_start=534
  _globals['_ESTATISTICASRESPONSE']._serialized_end=684
  _globals['_STREAMINGSERVICE']._serialized_start=687
  _globals['_STREAMINGSERVICE']._serialized_end=1229
# @@protoc_insertion_point(module_scope)
